version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: youtube-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    networks:
      - youtube-network
  
  frontend:
    build:
      context: ./frontend
    container_name: youtube-frontend
    ports:
      - "5500:5500"
    depends_on:
      - backend
    networks:
      - youtube-network

networks:
  youtube-network:
    driver: bridge
